# Setup
title:               Math 50
tagline:             'Linear regression modeling'
description:         'A course on linear regression modeling techniques and applications.'
url:                 none
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ethan Levien
  email:             ethanlevien@gmail.com

# Gems
plugins:
  - jekyll-paginate



# # Custom vars
# version:             1.1.0
# google_analytics_id: #UA-XXXX-Y
